config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'orders/index'
    get 'orders/show'
    get 'orders/new'
  end
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'admin' => 'admin/homes#top'
  get 'thanks' => 'public/orders#thanks'
  get 'customers/confirmation' => 'public/customers#confirmation'
  scope module: :public do
    resources :addresses
    resources :items, :only => [:index, :show]
    delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items
    resources :orders
    post 'orders/confirm' => 'orders#confirm'
    

    resource :customers, path: "customers/my_page", :only => [:show]
    resource :customers, :only => [:edit, :update]
  #get 'customers/mypage' => 'customers#show'
  patch 'withdrawal' => 'customers#withdrawal', as: 'withdrawal'
  end
  devise_for :customers, controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}
  namespace :admin do
   resources :genres
   resources :items
   resources :customers
  end
end

app/models/address.rb
class Address < ApplicationRecord
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :orders
   has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  accepts_nested_attributes_for :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
   @customer = Customer.find(params[:id])
   @costomer.update(costomer_params)
   redirect_to customers_path
  end
   
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end


  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
   @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    Genre.update(genre_params)
    redirect_to admin_Genre_path(genre.id)
  end

  private
  # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @admins = Admin.all
  end
  
  def about
  end 
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

 def index
    @items = Item.all
 end

 def new
   @item = Item.new
 end

 def create
   @item = Item.new(item_params)
   @item.save
   redirect_to admin_items_path
 end

 def show
  @item = Item.find(params[:id])
 end

 def edit
  @item = Item.find(params[:id])
 end
 
 def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_items_path
 end

 private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div>ジャンル編集</div>
<div>ジャンル名</div>
<%= form_with model: @genre, url: admin_genres_path, local:true do |f| %>
<%= f.text_field :name %>
<%= f.submit '変更を保存' %>
<% end %>

app/views/admin/genres/index.html.erb
<div>ジャンル一覧・追加</div>
  <%= form_with model: @genre, url: admin_genres_path, local:true do |f| %>
  <div>ジャンル名</div>
   <%= f.text_field :name %>
   <%= f.submit '新規登録' %>
   <% end %>
<table>
  <thead>
    <tr>
      <th>ジャンル</th>
    </tr>
  </thead>
  <% @genres.each do |genre| %>
  <tbody>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genre.id) %></td>
    </tr>
  </tbody>
  <% end %>
 </table>

app/views/admin/items/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">商品編集</div>
 </div>
  <div class="row">
   <div class="col-md-6 mx-auto">
    <%= form_with model:@item, url:'/admin/items', local:true do |f| %>
     <div class="row">
      <div class="col-md-2">
       <p>商品画像</p>
      </div>
      <div class="col-md-10">
       <%= f.attachment_field :image %>
      </div>
     </div>
     <div class="row">
      <div class="col-md-2">
       <p>商品名</p>
      </div>
      <div class="col-md-10">
       <%= f.text_field :name %>
      </div>
     </div>
     <div class="row">
      <div class="col-md-2">
       <p>商品説明</p>
      </div>
      <div class="col-md-10">
       <%= f.text_area :introduction %>
      </div>
     </div>
     <div class="row">
      <div class="col-md-2">
       <p>ジャンル</p>
      </div>
      <div class="col-md-10">
    　　<%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "選択してください"} %>
      </div>
     </div>
     <div class="row">
      <div class="col-md-2">
       <p>税抜価格</p>
      </div>
      <div class="col-md-10">
       <%= f.text_field :price %>
      </div>
     </div>
      <%= f.radio_button :is_active, '販売中' %>
      <%= f.label :is_active, '販売中', value: true %>
      <%= f.radio_button :is_active, '販売停止中' %>
      <%= f.label :is_active, '販売停止中', value: false %>
     <div><%= f.submit '変更を保存' %></div>
     <% end %>
    </div>
   </div>
 </div>

app/views/admin/items/index.html.erb
<div class="container">
商品一覧
<%= link_to "新規登録", new_admin_item_path %>
<div class="row">
 <table class="table">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
   </thead>
  <% @items.each do |item| %>
  <tbody>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name,admin_item_path(item.id) %></td>
      <td><%= item.price %></td>
      <td><%= item.genre.name %></td>
      <td><%= item.is_active %></td>
    </tr>
  </tbody>
  <% end %>
</table>
 </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">商品新規登録</div>
 </div>
  <div class="row">
   <div class="col-md-6 mx-auto">
    <%= form_with model:@item, url:'/admin/items', local:true do |f| %>
     <div class="row">
      <div class="col-md-2">
       <p>商品画像</p>
      </div>
      <div class="col-md-10">
       <%= f.attachment_field :image %>
      </div>
     </div>
     <div class="row">
      <div class="col-md-2">
       <p>商品名</p>
      </div>
      <div class="col-md-10">
       <%= f.text_field :name %>
      </div>
     </div>
     <div class="row">
      <div class="col-md-2">
       <p>商品説明</p>
      </div>
      <div class="col-md-10">
       <%= f.text_area :introduction %>
      </div>
     </div>
     <div class="row">
      <div class="col-md-2">
       <p>ジャンル</p>
      </div>
      <div class="col-md-10">
    　　<%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "選択してください"} %>
      </div>
     </div>
     <div class="row">
      <div class="col-md-2">
       <p>税抜価格</p>
      </div>
      <div class="col-md-10">
       <%= f.text_field :price %>
      </div>
     </div>
      <%= f.radio_button :is_active, '販売中' %>
      <%= f.label :is_active, '販売中', value: true %>
      <%= f.radio_button :is_active, '販売停止中' %>
      <%= f.label :is_active, '販売停止中', value: false %>
     <div><%= f.submit '新規登録' %></div>
     <% end %>
    </div>
   </div>
 </div>

app/views/admin/items/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">商品詳細</div>
 </div>
 <div class="row">
  <div class="col-md-2">
   <%= attachment_image_tag @item, :image, :fill, 100, 100, format: 'jpeg' %>
  </div>
 </div>
 <div class="row">
  <div class="col-md-2">
   <p>商品名</p>
  </div>
  <div class="col-md-10">
   <%= @item.name %>
  </div>
 </div>
<div class="row">
  <div class="col-md-2">
   <p>商品説明</p>
  </div>
  <div class="col-md-10">
   <%= @item.introduction %>
  </div>
 </div>
 <div class="row">
  <div class="col-md-2">
   <p>ジャンル</p>
  </div>
  <div class="col-md-10">
   <%= @item.genre.name %>
  </div>
 </div>
<div class="row">
  <div class="col-md-2">
   <p>税込価格</p>
   <p>(税抜価格)</p>
  </div>
  <div class="col-md-10">
    <p><%= (@item.price*1.08).to_i %></p>
    <p><%= @item.price %></p>
  </div>
 </div>
 <div class="row">
  <div class="col-md-2">
   <p>販売ステータス</p>
  </div>
  <div class="col-md-10">
   <%= @item.is_active %>
  </div>
 </div>
　<div><%= link_to "編集する",edit_admin_item_path(@item.id) %></div>
</div>